version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "09:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "⬆️"
